monitor=,preferred,auto,1

exec-once = waybar
exec-once = hyprpaper
exec-once = swaync

input {
    kb_layout = us
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
}

decoration {
    rounding = 8
    blur = yes
    blur_size = 5
}

bind = SUPER, RETURN, exec, kitty
bind = SUPER, Q, killactive
bind = SUPER, E, exec, thunar
bind = SUPER, SPACE, exec, wofi --show drun
bind = SUPER, F, fullscreen
bind = SUPER, M, exit

# Volumen
binde = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
binde = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bind = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle

# Brillo
binde = , XF86MonBrightnessUp, exec, brightnessctl set +5%
binde = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

# Apagar/Suspender
bind = SUPER, P, exec, poweroff
bind = SUPER+SHIFT, P, exec, systemctl suspend

# Movement
bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d

# Workspaces
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER+SHIFT, 1, movetoworkspace, 1
bind = SUPER+SHIFT, 2, movetoworkspace, 2
bind = SUPER+SHIFT, 3, movetoworkspace, 3
bind = SUPER+SHIFT, 4, movetoworkspace, 4
bind = SUPER+SHIFT, 5, movetoworkspace, 5